# Generated by Django 5.0.4 on 2024-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulacaoVeiculo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("valor_veiculo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_entrada", models.DecimalField(decimal_places=2, max_digits=5)),
                ("prazo_financiamento", models.IntegerField()),
            ],
        ),
    ]
