# Generated by Django 5.0.4 on 2024-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanciamentoVeiuclos",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("valor_veiculos", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "entrada_veiculos",
                    models.DecimalField(decimal_places=2, max_digits=2),
                ),
                ("prazo_financiamento", models.IntegerField()),
            ],
        ),
    ]
