# Generated by Django 5.0.4 on 2024-04-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financiamento_veiculos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FinanciamentoVeiuclos",
            new_name="FinanciamentoVeiculos",
        ),
    ]
